第四章表单和HTML辅助方法/输出页面链接/Controllers/Default1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace 输出页面链接.Controllers
{
    public class Default1Controller : Controller
    {
        // GET: Default1
        public ActionResult Index(int id)
        {
            ViewBag.id = id;
            return View();
        }
    }
}

第四章表单和HTML辅助方法/输出页面链接/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace 输出页面链接.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index(string bb)
        {
            ViewBag.show = bb;
            return View();
        }
        public ActionResult Register()
        {

            return View();
        }
    }
}

第四章表单和HTML辅助方法/输出页面链接/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @Html.ActionLink("首页", "Index",new { bb="首页"})
    <br />
    @Html.ActionLink("注册", "Register")
    <br />
    @Html.ActionLink("购物车", "Index", "Default1",new { id=1},new { })
    <br />
    <p>@ViewBag.show</p>
</body>
</html>

第四章表单和HTML辅助方法/输出页面链接/Views/Default/Register.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
  <h1>这里是注册</h1>
    @Html.ActionLink("首页","Index");
</body>
</html>

第四章表单和HTML辅助方法/输出页面链接/Views/Default1/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>@ViewBag.id</h1>
    @Html.ActionLink("首页","Index","Default")
</body>
</html>